# The URL the site will be built for
base_url = "https://myga.am"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

output_dir = "dist"
default_language = "en"

taxonomies = [
    {name = "tags", feed = true},
    {name = "categories", feed = true}
]

## Configure website languages.
[languages]

[languages.en]
title = "Kanach Yerevan"
build_search_index = true

[languages.ru]
title = "Kanach Yerevan"
build_search_index = true

[languages.hy]
title = "Կանաչ Երևան"
build_search_index = true

[translations]
footer = "Kanach Yerevan is a social movement that aims to make Yerevan a greener, more sustainable and more livable city."
language_name = "English"
translation = "Translation"
footer_trees = "Trees"
footer_birds = "Birds"
footer_lawns = "Lawns"
footer_codes = "Codes"
footer_insects = "Insects"
footer_join = "Join Us"
footer_events = "Events"
footer_dir = "Green Directory"
footer_learn = "Learn"
footer_connect = "Connect"
footer_act = "Act"
footer_org = "Organization"
footer_groups = "Local Groups"
footer_report = "Report Damage"
footer_map = "Map the Trees"
footer_team = "Team and Board"
footer_press = "Press"
footer_myga = "Make Yerevan Green Again!"
footer_blog = "Blog"
footer_leaves = "Leaves"
footer_about = "A platform for coordinating efforts to protect Yerevan's green spaces."
guides_bmp = "Best Management Practices"
guides_current = "Current Legislation"
guides_international = "International Standards (Reference)"
guides_proposed = "Proposed Amendments (Kanach Drafts)"
nav_more = "Read More"
nav_guidelines = "Guidelines"
nav_journal = "Journal"
nav_monitor = "Monitor"
nav_about = "About"
nav_action = "Take Action"
home_report = "Report a problem"
home_guidelines = "Read Guidelines"
home_trees_mapped = "Trees mapped"
home_trees_healthy = "Healthy"
home_trees_users = "Volunteers"
page_comments = "If you have any comments or suggestions, please send them to our <a href='/action/join/'>Telegram chat</a>."

[languages.ru.translations]
footer = "Kanach Yerevan это общественное движение, целью которого является сделать Ереван более зелёным, устойчивым и пригодным для жизни городом."
language_name = "Русский"
translation = "Перевод"
footer_trees = "Деревья"
footer_birds = "Птицы"
footer_lawns = "Газоны"
footer_codes = "Законы"
footer_insects = "Насекомые"
footer_join = "Присоединяйтесь"
footer_events = "События"
footer_dir = "Каталог"
footer_learn = "Изучай"
footer_connect = "Присоединяйся"
footer_act = "Действуй"
footer_org = "Команда"
footer_groups = "Локальные группы"
footer_report = "Сообщить о проблеме"
footer_map = "Карта деревьев"
footer_team = "Команда"
footer_press = "Прессе"
footer_myga = "Сделаем Ереван снова зелёным!"
footer_blog = "Блог"
footer_leaves = "Листья"
footer_about = "Платформа для координации усилий по защите зеленого фонда Еревана."
guides_bmp = "Лучшие методы управления"
guides_current = "Действующее законодательство"
guides_international = "Международные стандарты"
guides_proposed = "Предлагаемые поправки (наши проекты)"
nav_more = "Читать далее"
nav_guidelines = "Стандарты"
nav_journal = "Журнал"
nav_monitor = "Статус"
nav_about = "О нас"
nav_action = "Действуй"
home_report = "Сообщить о проблеме"
home_guidelines = "Открыть справочники"
home_trees_mapped = "Деревьев на карте"
home_trees_healthy = "Здоровых"
home_trees_users = "Волонтёров"
page_comments = "Если у вас есть замечания или предложения, пожалуйста, отправляйте их в <a href='/action/join/'>наш Telegram чат</a>."

[languages.hy.translations]
footer = "«Կանաչ Երևանը» հասարակական շարժում է, որի նպատակն է Երևանը դարձնել ավելի կանաչ, կայուն և բնակելի քաղաք։"
language_name = "Հայերեն"
translation = "Լեզուներ"
footer_trees = "Ծառերը"
footer_birds = "Թռչունները"
footer_lawns = "Ճահիճները"
footer_codes = "Օրենքները"
footer_insects = "Սողունները"
footer_join = "Միացեք մեզ"
footer_events = "Միջոցառումներ"
footer_dir = "Կանաչ Ցուցակ"
footer_learn = "Սովորի՛ր"
footer_connect = "Միացի՛ր"
footer_act = "Գործի՛ր"
footer_org = "Նախագիծ"
footer_groups = "Տեղական խմբեր"
footer_report = "Ահազանգել"
footer_map = "Քարտեզագրել"
footer_team = "Թիմ և խորհուրդ"
footer_press = "Մամուլ"
footer_myga = "Կանաչ դարձնենք Երևանը կրկին!"
footer_blog = "Բլոգ"
footer_leaves = "Տերևներ"
footer_about = "Երևանի կանաչ ֆոնդի պաշտպանության ջանքերը համակարգող հարթակ։"
guides_bmp = "Լավագույն կառավարման պրակտիկա"
guides_current = "Ընթացիկ օրենսդրություն"
guides_international = "Միջազգային ստանդարտներ"
guides_proposed = "Առաջարկվող փոփոխություններ (Կանաչ նախագծեր)"
nav_more = "Կարդալ ավելին"
nav_guidelines = "Ուղեցույց"
nav_journal = "Անդրադարձ"
nav_monitor = "Մշտադիտարկում"
nav_about = "Մեր մասին"
nav_action = "Գործել"
home_report = "Հայտնել խնդրի մասին"
home_guidelines = "Կարդալ ուղեցույցները"
home_trees_mapped = "Քարտեզագրված ծառեր"
home_trees_healthy = "Առողջ"
home_trees_users = "Կամավորներ"
page_comments = "Եթե ունեք որևէ մեկնաբանություն կամ առաջարկություն, խնդրում ենք ուղարկել մեր <a href='/action/join/'>Telegram զրուցարան</a>։"
